apiVersion: v1
kind: Secret
metadata:
  name: loja-veloz-secrets
  namespace: loja-veloz
type: Opaque
stringData:
  DATABASE_USER: "admin"
  DATABASE_PASSWORD: "admin123"
  RABBITMQ_USER: "admin"
  RABBITMQ_PASSWORD: "admin123"
  PAYMENT_GATEWAY_API_KEY: "fake-key-dev"
